name: flutter_ui
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ui:
    path: ./ui/

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/index-icon/icon_nav_feedback.png
    - assets/images/index-icon/icon_nav_form.png
    - assets/images/index-icon/icon_nav_layout.png
    - assets/images/right-icon.png

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/font-icon/iconfont.ttf